/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#465b30",
        graphite: "#1A1A1A",
        "surface-variant": "#e5e2db",
        "on-surface-variant": "#44483e",
        "primary-fixed": "#d2ebb3",
        "on-tertiary": "#ffffff",
        "grey-green-status": "#DDE7DA",
        "secondary-fixed": "#e8e2d7",
        surface: "#fcf9f2",
        "on-primary-fixed-variant": "#384d23",
        "primary-container": "#5e7446",
        tertiary: "#684f46",
        background: "#fcf9f2",
        "surface-dim": "#dcdad3",
        "inverse-on-surface": "#f3f0e9",
        "secondary-fixed-dim": "#ccc6bb",
        "on-error-container": "#93000a",
        "on-primary-container": "#dff9c0",
        "inverse-primary": "#b6cf99",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#594139",
        "olive-soft": "#EAF0E6",
        "on-tertiary-fixed": "#291710",
        "on-secondary-container": "#68645b",
        "surface-bright": "#fcf9f2",
        "surface-tint": "#4f6538",
        "surface-container-high": "#ebe8e1",
        "on-background": "#1c1c18",
        "on-surface": "#1c1c18",
        "border-light": "#E5DED3",
        "on-secondary-fixed-variant": "#4a463f",
        "surface-container": "#f1eee7",
        "tertiary-container": "#82675e",
        "surface-container-highest": "#e5e2db",
        "surface-container-low": "#f6f3ec",
        "primary-fixed-dim": "#b6cf99",
        "surface-container-lowest": "#ffffff",
        secondary: "#625e55",
        "white-card": "#FFFFFF",
        "tertiary-fixed-dim": "#e1bfb4",
        "muted-text": "#756F67",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-primary-fixed": "#0e2000",
        "on-tertiary-container": "#ffece6",
        "on-secondary-fixed": "#1e1b15",
        "secondary-container": "#e8e2d7",
        "on-primary": "#ffffff",
        "outline-variant": "#c5c8bb",
        "inverse-surface": "#31312c",
        outline: "#75786d",
        "tertiary-fixed": "#fedbcf",
        "olive-dark": "#3F5630",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        base: "8px",
        "container-padding-mobile": "20px",
        gutter: "12px",
        "card-gap": "16px",
        "section-gap": "32px",
      },
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-md-mobile": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-xl": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "headline-md-mobile": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "16px", letterSpacing: "0.01em", fontWeight: "500" },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": [
          "32px",
          { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        "headline-xl-mobile": [
          "26px",
          { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg": [
          "24px",
          { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" },
        ],
        "headline-lg-mobile": [
          "22px",
          { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
